apiVersion: v1
data:
  haproxy.cfg: |+
    global
      daemon
      maxconn 256

    defaults
      mode tcp
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms

    frontend the-frontend
      bind *:80
      default_backend the-backend

    backend the-backend
      server google.com-80 google.com:80 maxconn 32 check
      server ibm.fr-80 ibm.fr:80 maxconn 32 check

kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-10T12:55:38Z"
  name: haproxy
  namespace: default
  resourceVersion: "227785"
  uid: b3191744-7deb-426b-84d2-56641391965d